### ISSUE TITLE
Check out puppet-js-patches custom element

### ISSUE THREAD

**Issue by miyconst** [Polyjuice/starcounter-debug-aid#20]
@tomalec, here are the branches for PuppetJs, puppet-client and starcounter-debug-aid.

PuppetJs: https://github.com/PuppetJs/PuppetJs/tree/send-receive-events
puppet-client: https://github.com/PuppetJs/puppet-client/tree/starcounter-debug-aid
starcounter-debug-aid: https://github.com/Polyjuice/starcounter-debug-aid/tree/send-receive-events

Steps to test the end result:

1. Replace files PuppetJs/src/puppet.js, puppet-client/src/puppet-client.html, starcounter-debug-aid/src/starcounter-debug-aid.html in your sys directory.
2. Copy starcounter-debug-aid/src/puppet-js-patches.html file to your sys directory.
3. Run Launcher and any other Polyjuice application.
4. Open debug-aid, there should be Network tab which contains all of the puppet-js requests and responses.

Please, check out the code and merge with your changes.
Contact me if you have any questions or need any help.

**Comment by tomalec** [comment]
After the first look at code (I'll review it deeper on Monday), I have few notes regarding https://github.com/PuppetJs/PuppetJs/commit/fe1023c8f8b2ae0cceee3242cb060005a62cc394

1. What `var p` stands for?
2. In my opinion for better responsibility separation, DRY, and performance 

  > `puppet.send` is supposed to by highly efficient and able to process as many operation per sec as possible - to reduce break in strong consistency, and reduce transformation needed to get eventual consistency
 we should move `new Date()` to peer that listens to puppet. So all that object (`p`, and `Date`) creation will happen only when `<starcounter-debug-aid>` ask for.

3. Why have you removed `NoQueue`? @warpech suggest it to keep code flow more consistent regardless of type of JSON Patch processor chosen.

4. Once you are done with changes, and stable with API and set of features, could you add note on README.md and automated test for it?

**Comment by miyconst** [comment]
1. It was a wrapper for url and date values. Removed date and pass url only, no more `var p`.
2. Removed `new Date()` and `var p = { ... }`, pass url as a second parameter.
3. I didn't remove it. I used files from SC installation folder. It looks like they were outdated. Reverted my changes in git, then pushed it back on top of the latest commit.
4. Sure, but edit README.md of which project? Where and what automated test should I add?

**Comment by tomalec** [comment]
### PuppetJs
1. Cool, 
2. thanks, 
3. I know it leads to [repolepsy](repolepsy.org) ;) but we try to keep separated components in different repos, and it happens we just change something  in one repo, and does not update dependencies in all other that needs it (unless it's breaking change). From the same reason, we also try to avoid ad hoc changes to dependencies loaded from bower (e.g. we do not submit changes to `/bower_components/*`,`Polyjuice/StaticFiles/sys/`, that did not come with `bower update`)
4. Because of what I described above, could you mention in each repo that you added/changed features/API. I think it would be nice to have test for it at least in PuppetJs/PuppetJs.
5. Once you are done, could you describe solution at https://github.com/PuppetJs/PuppetJs/issues/1 ?
6. Have you thought about usage of EventTarget API that @warpech implemented? (`this.dispatchEvent`) it could make listening to the changes cleaner, however it gives an overhead of `Event` object creation. It would also be direct solution for https://github.com/PuppetJs/PuppetJs/issues/1
7. Have you thought about moving `onSent` into `PuppetNetworkChannel#xhr`
8. Now we do have `puppet.onRemoteChange`, `puppet.onPatchReceived`, `puppet.onPatchSent`, `puppet.network.onSend`, `puppet.network.onReceive` - It's quite confusing, what is what and called when.

  From what I get: 
   - `puppet.onRemoteChange` is called as often as `puppet.onPatchReceived` but the second one just gets non-parsed JSON, plus `url` - I suggest unifying those
   - `puppet.network.onReceive` is just a reference to `puppet.handleRemoteChange` in network scope
   - `puppet.network.onSend` is just a reference to `puppet.onPatchSent`


9. You call `onPatchSent` before establishing connection (even if no patch was send). For consistency I would either call `on...Receive` once connection is establish, and consider changing the callback name, or do not call it then - as PuppetJs user can get it, just before `Puppet` constructor (`onInitialCallToBeSend(null, url); new Puppet({url: url});`)


### `<puppet-client>`
1.  As in 8. could we unify callback/event names? as now we get `<puppet-client>.patchreceived`, `<puppet-client>.patchsent`
2. Even if we won't use PuppetJs `EventTarget` API for send/receive patches, we could (and in my opinion should) use it for `<puppet-client>`. As it's a `HTMLElement`, we get `EventTarget` API natively, and `puppet-client` is to serve as DOM interface/wrapper for `Puppet`


### `<starcounter-debug-aid>`

1. Maybe there is a nice way to share `<puppet-js>` getter with `puppet-js-setting`?
2. I think instead of writing `<div class="puppet-js-patches">` and repeating `.puppet-js-patches` so many times in CSS, it would be cleaner to use `:host` selector. BTW as it's ShadowDOM ,entire CSS is scoped to your element (unless specified otherwise with `:content`), so you don't need to repeat event `:host` so many times, you need it just to style element itself.
3. We need a closure here https://github.com/Polyjuice/starcounter-debug-aid/blob/send-receive-events/src/puppet-js-patches.html#L90  (CSS is scoped in ShadowDOM, but JS is not)
4. I do not understand exact flow in your https://github.com/Polyjuice/starcounter-debug-aid/blob/send-receive-events/src/puppet-js-patches.html#L133, so let's discuss it on HO :)

**Comment by miyconst** [comment]
@tomalec all of the points except the PuppetJs socket test are done.
Please, close the issue if you have no more points to fix.

**Comment by tomalec** [comment]
- PuppetJS marged at [PuppetJs/PuppetJs@17732da7](https://github.com/PuppetJs/PuppetJs/tree/17732da7c426f52fca759f8176eadde243ee8fe9)
 - puppet-client merged at [PuppetJs/puppet-client@c846f25d](https://github.com/PuppetJs/puppet-client/tree/c846f25d205abbfbbc01fe400386180b402b4bc2)
 - starcounter-debug-aid merged at [starcounter-debug-aid@8b7cc1eade](https://github.com/Polyjuice/starcounter-debug-aid/tree/8b7cc1eadeb57cf6e469aa065125413342863b2a)
